// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package cachedb

import (
	"context"
)

const getEntry = `-- name: GetEntry :one
SELECT data, expires_at FROM cache_entries WHERE key = ?
`

type GetEntryRow struct {
	Data      []byte
	ExpiresAt int64
}

func (q *Queries) GetEntry(ctx context.Context, key string) (GetEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getEntry, key)
	var i GetEntryRow
	err := row.Scan(&i.Data, &i.ExpiresAt)
	return i, err
}

const pruneExpired = `-- name: PruneExpired :exec
DELETE FROM cache_entries WHERE expires_at < ?
`

func (q *Queries) PruneExpired(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, pruneExpired, expiresAt)
	return err
}

const setEntry = `-- name: SetEntry :exec
INSERT OR REPLACE INTO cache_entries (key, data, expires_at)
VALUES (?, ?, ?)
`

type SetEntryParams struct {
	Key       string
	Data      []byte
	ExpiresAt int64
}

func (q *Queries) SetEntry(ctx context.Context, arg SetEntryParams) error {
	_, err := q.db.ExecContext(ctx, setEntry, arg.Key, arg.Data, arg.ExpiresAt)
	return err
}
